# Generated by Django 3.2.18 on 2023-05-01 14:45

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20230501_1349'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='city',
            field=models.CharField(max_length=25, default='N/A'),
        ),
        migrations.AlterField(
            model_name='post',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, default='NA'),
        ),
    ]
