# Generated by Django 3.2.18 on 2023-04-12 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
