# Generated by Django 3.2.18 on 2023-04-30 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='region',
        ),
    ]
